### ISSUE TITLE
Request: Use fan art instead of channel logo on the Channel Information Screen

### ISSUE THREAD

**Issue by bagobones** [realriot/tvheadend-ng.bundle#17]
There is some easy free Python code being uses in some of the other plugins to pull TVDB data.. by querying by the Show title in many cases it is easy to pull a fan art picture for the show, instead of displaying a giant version of the channel logo.

If the episode data is present in tvheadend it might be able to pull even more detailed data.

**Comment by realriot** [comment]
This part already existed within one of the last version. This made the plugin much slower since this logic shouldn't be handled by the plugin rather than tv-headend.
