### ISSUE TITLE
Request: Create a recordings view that groups by Show Title

### ISSUE THREAD

**Issue by bagobones** [realriot/tvheadend-ng.bundle#18]
The simple alphabetical list gets rather long fast once you have several recordings for each show.

**Comment by realriot** [comment]
If someone has a hint how to realize it in a nice and easy way...

**Comment by fritz-fritz** [comment]
I'm looking into this... Shouldn't be too hard.

**Comment by realriot** [comment]
Nice, if you "have" something to pull. Tell us :-)
