### ISSUE TITLE
Support TVH_HTTP_ROOT path

### ISSUE THREAD

**Issue by ShadowXVII** [realriot/tvheadend-ng.bundle#19]
My tvheadend is proxied through a https nginx box. As part of this setup, I use the /tv/ identifier in the URL which is set as the TVH_HTTP_ROOT in the Tvheadend configuration defaults (running Debian jessie).

The plugin for plex errors as it must assume the path is /, where it infact needs to have a base of /tv. If I put /tv on the port it works (config included below).

![image](https://cloud.githubusercontent.com/assets/446329/5560510/e420c038-8de3-11e4-9925-001ba5165bc4.png)

A new field to specify the TVH_HTTP_ROOT should be added to accommodate for this field (defaulting to /), or otherwise could utilise the htsp "hello" to retrieve the web root.

**Comment by realriot** [comment]
I'll take of this within one of the next versions

**Comment by realriot** [comment]
Added within latest commit
