### ISSUE TITLE
Playback stops after a few seconds on the Plex android app

### ISSUE THREAD

**Issue by Queuecumber** [realriot/tvheadend-ng.bundle#20]
When I start a tv stream on the Plex android app, it plays back for a few seconds and then stops (as though the video has ended). Oddly, if I use the same app to cast to my chromecast, it plays back without stopping but freezes every so often. Any idea how I can fix this?

**Comment by ShadowXVII** [comment]
I found this too. Turning off the experimental player in the settings allowed it to play normally. Checking the verbose logging in Plex suggest that its got a "negative play time " but I'm not 100% familiar with the log messages.

**Comment by ralphte** [comment]
I am unable to play even after turning off experimental player. Have not really figured it out kinda sucks at this point.

**Comment by realriot** [comment]
Plex changed the way it handles "live" streams. Please reopen this ticket when the failure still exists. Please deliver logs!

**Comment by VijayMeena701** [comment]
im facing the same issue. the player stops automatically after a few seconds. i dont even have experimental player turned on.
