### ISSUE TITLE
Picons not shown in Plex - HTTP 401 for picons

### ISSUE THREAD

**Issue by quasipapa** [realriot/tvheadend-ng.bundle#22]
Error:
I configured picons for the channels in tvheadend, The picons are shown in tvheadend, but not in Plex,

Reason:
The access for the path /imagecache is limited by tvheadend to authorized users. Since no authorization information is coded in the access path for picons, you get http 401 when no anonymous user exists for the IP of the Plex-Server.

Solution:
By configuration in tvheadend: Create an anonymous user (Username:* / Password:* / Network prefix 127.0.0.1/32 (when plex is running on the same server as tvheadend).

By tvheadend-ng (preferred): Pass HTTP basic authentication credentials in the URL for picons.

**Comment by sanitariu** [comment]
That's a bug in tvheadend-ng.bundle.
You must edit __init__.py
On line 143 change iconurl to be like:

result['iconurl'] = 'http://%s:%s@%s:%s/%s' % (Prefs['tvheadend_user'], Prefs['tvheade
nd_pass'], Prefs['tvheadend_host'], Prefs['tvheadend_web_port'], epg['channelIcon'])
