### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by gfucka** [realriot/tvheadend-ng.bundle#26]
Hi 
I have 
tvh version 3.4.28~geb79aee~trusty
plex version 2.3.20.

I install the plugin in plex but when I try tu run it I have 
Unknow error message.

What is the problem??

Thanks

**Comment by Ocrimops** [comment]
I had the same issue, running the latest stable version of tvheadend. Updated tvheadend to latest unstable version and it worked for me.

**Comment by gfucka** [comment]
Ok I try.
Thank you

2015-03-18 11:52 GMT+01:00 Ocrimops <notifications@github.com>:

> I had the same issue, running the latest stable version of tvheadend.
> Updated tvheadend to latest unstable version and it worked for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realriot/tvheadend-ng.bundle/issues/26#issuecomment-82891311>
> .
>



-- 
Dott. Giosia Gentile

**Comment by realriot** [comment]
The plugins tries to make a API version check. If it fails for an unknown reason it quits this request. A new error check will be pushed within the next release.
