### ISSUE TITLE
Error while opening file

### ISSUE THREAD

**Issue by Ocrimops** [realriot/tvheadend-ng.bundle#27]
Using latest unstable version of tvh and latest pms I get the error-message 'Error while opening file', selecting a channel to watch.
Environment: Mac mini with latest OSX
Stream channel directly via VLC from tvh works.
Any idea where I could investigate?

**Comment by Ocrimops** [comment]
Updated my Plex Media Center as well which is at same machine as the Plex Server.
Now the error message gets a bit more verbose:
Unable to play media
Please check that this file exists and the necessary drive is mounted

... sometimes followed by:
Playback failed
One or more items failed to play

Within web-view of Plex Server it works.

**Comment by catatonicChimp** [comment]
I just started using the tvheadend plugin.. I get the exact same error, @Ocrimops did you manage to solve your problem?

I am running plex server on ubuntu 0.9.12.1.1079
I am running the latest unstable tvheadend 3.9.2789~geb6cdcb~trusty
It works fine if I use the plex web player, but through plex home theatre (osx) it comes up with the error:
"Unable to play media"
"please check that this file exists and the necessary drive is mounted"

**Comment by realriot** [comment]
Cannot reproduce this error, sorry. I'm currently running this plugin under mac osx with a tvheadend located in a vm.

**Comment by jaarsa** [comment]
Hi!

I am experimenting the same problem as catatonicChimp above.

My server is running tvheadend 4.0.5-17, and PMS 0.9.12.9. (both on the same system) with latest tvheadend-ng.bundle.

All channesl stream fine using the web-browser. I also have an OpenElec systen 5.0.8 which is working flawlessly with TVheadend plugin. All channels also streams perfect in VLC.

The errors ONLY appear when using PHT on a both Mac and Windows.
Quite frustrating since it's such a greate plugin and It's not working with the system it's actually meant for.

Is this a PHT or a Channel (tvheadend-ng.bundle) problem?

If you need any logs for looking into this I'd gladly help you out?

**Comment by fritz-fritz** [comment]
I'm experiencing the EXACT same situation as @jaarsa. My PMS and TVH server are both on a single ubuntu server. Streaming and transcoding is working great to both web and iOS. Cannot stream to PHT on Windoze nor Mac. Getting the "Unable to Play, check if the drive is mounted" error.

**Comment by fritz-fritz** [comment]
@realriot I have included the relevant log information below. Seems to be a 401 response from TVH. Opening that url with VLC prompts for the user credential and then begins playing the stream. It seems the credential is somehow lost in the request from the PHT client. I'll take a look and see if its a simple fix

###### TVH Log
```
2015-08-27 01:09:43.841 http: 10.0.1.6: HTTP/1.1 GET /stream/channel/7caa035582d59d86e921e21a27f2f6a1 -- 401
```
###### PHT Log
```
01:09:48 T:5066760192   ERROR: CPlexTextureCacheJob::CacheTexture unable to open input file plexserver://<<40 alpha numeric characters>>/photo/:/transcode?height=320&url=http%3a%2f%2fresources-cdn.plexapp.com%2fimage%2fsource%2fcom.plexapp.plugins.tvheadend-ng.jpg%3fh%3dNone&width=320
01:09:48 T:140735293690624  NOTICE: DVDPlayer: Opening: plexserver://<<40 alpha numeric characters>>/video/tvheadend-ng/:/function/PlayMedia?function_args=Y2VyZWFsMQoxCmRpY3QKMQpzOTEKaHR0cDovL3BsZXg6cGxleEAxMC4wLjEuODo5OTgxL3N0cmVhbS9jaGFubmVsLzdjYWEwMzU1ODJkNTlkODZlOTIxZTIxYTI3ZjJmNmExP3Byb2ZpbGU9cGFzc3MzCnVybHIwCg__
01:09:48 T:140735293690624 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
01:09:48 T:5144842240  NOTICE: Thread CDVDPlayer start, auto delete: false
01:09:48 T:5144842240  NOTICE: Creating InputStream
01:09:48 T:5144842240   ERROR: Open - failed to open source <plexserver://<<40 alpha numeric characters>>/video/tvheadend-ng/:/function/PlayMedia?function_args=Y2VyZWFsMQoxCmRpY3QKMQpzOTEKaHR0cDovL3BsZXg6cGxleEAxMC4wLjEuODo5OTgxL3N0cmVhbS9jaGFubmVsLzdjYWEwMzU1ODJkNTlkODZlOTIxZTIxYTI3ZjJmNmExP3Byb2ZpbGU9cGFzc3MzCnVybHIwCg__>
01:09:48 T:5144842240   ERROR: CDVDPlayer::OpenInputStream - error opening [plexserver://<<40 alpha numeric characters>>/video/tvheadend-ng/:/function/PlayMedia?function_args=Y2VyZWFsMQoxCmRpY3QKMQpzOTEKaHR0cDovL3BsZXg6cGxleEAxMC4wLjEuODo5OTgxL3N0cmVhbS9jaGFubmVsLzdjYWEwMzU1ODJkNTlkODZlOTIxZTIxYTI3ZjJmNmExP3Byb2ZpbGU9cGFzc3MzCnVybHIwCg__]
01:09:48 T:5144842240  NOTICE: CDVDPlayer::OnExit()
01:09:48 T:5144842240  NOTICE: CDVDPlayer::OnExit() deleting input stream
01:09:48 T:140735293690624   ERROR: Playlist Player: skipping unplayable item: 0, path [plexserver://<<40 alpha numeric characters>>/video/tvheadend-ng/:/function/createTVChannelObject?function_args=Y2VyZWFsMQo2CmRpY3QKZGljdApkaWN0Cmxpc3QKbGlzdApsaXN0CjUKczE3ClBsZXggSG9tZSBUaGVhdGVyczgKY3Byb2R1Y3RiMXM5CmNvbnRhaW5lcnMxNwpQbGV4IEhvbWUgVGhlYXRlcnM5CmNwbGF0Zm9ybXIxCnM4CmNoYW5pbmZvcjIKczcKY2hhbm5lbDgKczUKMDI6MDBzOAplcGdfc3RvcHMxMgpUaGUgQXZlbmdlcnNzOQplcGdfdGl0bGVzNQowMTowMHM5CmVwZ19zdGFydGIwczE3CnNlcnZpY2VfZW5jcnlwdGVkaTM2MDAwMDAKczEyCmVwZ19kdXJhdGlvbnMzNApUaGUgcGxvdCB0byBzcHJlYWQgYnVib25pYyBwbGFndWUuczE1CmVwZ19kZXNjcmlwdGlvbnMwCnMxMQplcGdfc3VtbWFyeXMxCjBzMTIKc2VydmljZV90eXBlMTMKczMyCjdjYWEwMzU1ODJkNTlkODZlOTIxZTIxYTI3ZjJmNmExczQKdXVpZHIzCnM0CnRhZ3N1MApzNwpib3VxdWV0aTAKczEyCmR2cl9wc3RfdGltZXI0CnM3CmVwZ2dyYWJiMXM3CmVuYWJsZWRzMwo0LjJzNgpudW1iZXJzMTAKNC4yIFdSQ0RUMnM0Cm5hbWVzMTMKaW1hZ2VjYWNoZS8zNnMxNQppY29uX3B1YmxpY191cmxyNQpzOApzZXJ2aWNlc2IxczcKZXBnYXV0b2kwCnMxMgpkdnJfcHJlX3RpbWVzNDgKaHR0cDovL2ltYWdlcy56YXAyaXQuY29tL3N0YXRpb25fbG9nby93cmNkdDIuZ2lmczQKaWNvbjIKczMyCjVlYjcyZGIyZDgxZjNhNjkxNGUzZDMzNWViNzQ0NzMzczMyCjZhYzVmNzU1ZTdmZmVhYTQzZjNkZTgxNGNiZWNkMzUxMQpzMjgKeG1sdHZ8STQ1NzM2LmxhYnMuemFwMml0LmNvbTEKczMyCjAyM2UyZGIzZjkwMWVlYmQ3NWE5NGY2MTRmZGEwZGY2cjAK]
01:09:48 T:140735293690624  NOTICE: CDVDPlayer::CloseFile()
01:09:48 T:140735293690624 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
01:09:48 T:140735293690624  NOTICE: DVDPlayer: waiting for threads to exit
01:09:48 T:140735293690624  NOTICE: DVDPlayer: finished waiting
```

**Comment by fritz-fritz** [comment]
This is weird. I checked the PMS logs for the plugin and found this:
```
2015-08-27 01:26:47,358 (7f6916ffd700) :  DEBUG (runtime:717) - Handling request GET /video/tvheadend-ng/:/function/createTVChannelObject?checkFiles=1&function_args=Y2VyZWFsMQo2CmRpY3QKZGljdApkaWN0Cmxpc3QKbGlzdApsaXN0CjUKczE3ClBsZXggSG9tZSBUaGVhdGVyczgKY3Byb2R1Y3RiMXM5CmNvbnRhaW5lcnMxNwpQbGV4IEhvbWUgVGhlYXRlcnM5CmNwbGF0Zm9ybXIxCnM4CmNoYW5pbmZvcjIKczcKY2hhbm5lbDgKczUKMDE6MzhzOAplcGdfc3RvcHMyNwpMYXRlIE5pZ2h0IFdpdGggU2V0aCBNZXllcnNzOQplcGdfdGl0bGVzNQowMDozN3M5CmVwZ19zdGFydGIwczE3CnNlcnZpY2VfZW5jcnlwdGVkaTM2NjAwMDAKczEyCmVwZ19kdXJhdGlvbnMzMQpDaHJpc3RpbmUgQmFyYW5za2k7IENvbGluIEpvc3QuczE1CmVwZ19kZXNjcmlwdGlvbnMwCnMxMQplcGdfc3VtbWFyeXMxCjBzMTIKc2VydmljZV90eXBlMTMKczMyCmE1N2VkZjg5NmEyYmY1ZDk3YmNkN2VmY2ZjZGJkOTUwczQKdXVpZHIzCnM0CnRhZ3N1MApzNwpib3VxdWV0aTAKczEyCmR2cl9wc3RfdGltZXI0CnM3CmVwZ2dyYWJiMXM3CmVuYWJsZWRzMwo0LjFzNgpudW1iZXJzOQo0LjEgV1JDRFRzNApuYW1lczEzCmltYWdlY2FjaGUvMzVzMTUKaWNvbl9wdWJsaWNfdXJscjUKczgKc2VydmljZXNiMXM3CmVwZ2F1dG9pMApzMTIKZHZyX3ByZV90aW1lczU1Cmh0dHA6Ly9pbWFnZXMuemFwMml0LmNvbS9zdGF0aW9uX2xvZ28vbmJjX2FmZmlsaWF0ZS5naWZzNAppY29uMgpzMzIKNmFjNWY3NTVlN2ZmZWFhNDNmM2RlODE0Y2JlY2QzNTFzMzIKNjhiNDg3NDgwYzZmOThjYzMxNTdjODUzNjFkNzJlZjIxCnMyOAp4bWx0dnxJMTk1NzgubGFicy56YXAyaXQuY29tMQpzMzIKZDg0ZjYxMmI5MjFlNmI0NDQ5YmFmNTM4ZDI2ZmY0NWZyMAo_
2015-08-27 01:26:47,363 (7f6916ffd700) :  DEBUG (runtime:814) - Found route matching /video/tvheadend-ng/:/function/createTVChannelObject
2015-08-27 01:26:47,363 (7f6916ffd700) :  DEBUG (runtime:143) - Calling function 'createTVChannelObject'
2015-08-27 01:26:47,462 (7f6916ffd700) :  CRITICAL (sandbox:303) - Exception when calling function 'createTVChannelObject' (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
TypeError: createTVChannelObject() got an unexpected keyword argument 'checkFiles'

2015-08-27 01:26:47,463 (7f6916ffd700) :  DEBUG (runtime:106) - Sending packed state data (113 bytes)
2015-08-27 01:26:47,463 (7f6916ffd700) :  DEBUG (runtime:918) - Response: [404] NoneType, 0 bytes
```

What's odd is that I can't find where this 'checkFiles' argument is coming from? It doesn't seem to anywhere within the channel's code... I'm digging through the forums to see what this is... but ultimately it seems like getting the channel to work with PHT again will be as simple adding an optional argument to the 'createTVChannelObject' method which is simply not used. This way python shouldn't complain...

**Comment by fritz-fritz** [comment]
After adding 'checkFiles = 0' as an argument to 'createTVChannelObject' the CRITICAL exception is fixed. Still haven't figured out why TVHeadend is giving a 401. I added logging above the Redirect in PlayMedia and I can confirm the credentials are passed. Using the same exact URL in VLC works. Streaming from every other client I have tried works. This seems like it may be a PHT bug.

**Comment by realriot** [comment]
I've added "checkFiles" in tjhe latest push... I noticed this failure by testing with PHT. Now I can view the TV channels.

I noticed an issue with AUDIO only channels (radio). These channel still cannot be played by PHT.

**Comment by jaarsa** [comment]
Does this mean that this plugin is working with PHT, or is it still a "Work in progress"? :)

**Comment by realriot** [comment]
Fine, come back if you have further problems and I will see if I can help you.
