### ISSUE TITLE
Is there a guide for this?

### ISSUE THREAD

**Issue by Cirion75** [realriot/tvheadend-ng.bundle#30]

**Comment by CarnalMischief** [comment]
If you mean how do you install the client / bundle 'tvheadend-ng.bundle '

https://support.plex.tv/hc/en-us/articles/201187656-How-do-I-manually-install-a-channel-
https://support.plex.tv/hc/en-us/articles/201106098

Once installed, restart the Plex server, then from the Plex server find the 'tvheadend' channel icon, hover over the channel and click the cogged wheel (settings). Enter your config settings so it can communicate with your TVHeadend Server.

Hope that points you in the right direction.

**Comment by realriot** [comment]
Pls have a look at the plex channel install guides mentioned in the post before.

**Comment by Cirion75** [comment]
I have tvheadend up an running. Plex also, and installed the bundle.... All
working great on XBMC since 2008? I dont remember when I started using
TVheadend.

That does not work.

The only info is api 15 needed. Since tvheadend is api 22, I was thingking
it shoul work. But I get a error message when starting the channel.

Is there a guide on how to set up the channel. What are the requirements.
Plex and Tvheadens versions? I am using latest stable on both.

What do I enter in the config? Is user required? I do not use users in my
setup. I have entered IP and port.

I'm lost.
19. juli 2015 15:18 skrev "CarnalMischief" <notifications@github.com>:

**Comment by CarnalMischief** [comment]
I could be wrong, but latest versions of Plex server should work regardless. BUT the stable version of TVHeadend is too old (3.4)  you'll have to download and compile the latest unstable version for yourself (eg. 3.9.?). I haven't tried the very latest ver 4.? so can't comment, yet.

**Comment by Cirion75** [comment]
I have the latest stable 4.
19. juli 2015 18:18 skrev "CarnalMischief" <notifications@github.com>:

**Comment by CarnalMischief** [comment]
Purely for the record I've just rechecked and I've actually been running 4.1.328 for the last couple of weeks (sorry my mistake). Just this second updated to 4.1.360 and it's still working with the client previous to current version.

**Comment by Cirion75** [comment]
As you can see, I have compiled and installed 4.1.360 (latest git).
I still get the error message, and I still have no idea on how to set the
plugin up.

I have attached a few screenshots.

2015-07-19 23:22 GMT+02:00 CarnalMischief <notifications@github.com>:

**Comment by CarnalMischief** [comment]
On my setup I've created 2 transcoding streaming profiles on the TVheadend server, Plex-General & Plex-Mobile, these are not needed you can use the default MPEP-TS Pass-Through. The TVHeadend client is configured on the Plex Server as per the attached screenshots. The current client doesn't work properly for me I get "The channel is not responding", so I'm currently still using the previous version which works perfectly. I also needed to create a null account for the picons and stuff to work with the previous version https://github.com/realriot/tvheadend-ng.bundle/issues/22.

Also check the Plex Forums, lots of info there too https://forums.plex.tv/discussion/95345/tv-headend-next-generation/p22

PS. Couldn't  see your screenshots, also couldn't figure out how to send PM's

![plex1of2](https://cloud.githubusercontent.com/assets/13293119/8790927/82c47f6e-2f4b-11e5-8665-162e8154e186.JPG)
![plex2of2](https://cloud.githubusercontent.com/assets/13293119/8790926/82c0961a-2f4b-11e5-924d-646e8285352f.JPG)

.
