### ISSUE TITLE
New API version

### ISSUE THREAD

**Issue by realriot** [realriot/tvheadend-ng.bundle#35]
TV-Headend offers a new API version. The actual release does not support this version. Until I've checked the dependencies you habe to wait to update to the latest tvh.

**Comment by realriot** [comment]
Latest API version is 18. If someone can confirm that this release works with 18 without any changes I can update it asap.

**Comment by Daegalus** [comment]
To my knowledge, the latest is v22, and I think 4.0 requires minimum v20 support, but i could be wrong.

https://tvheadend.org/projects/tvheadend/wiki/Htsp

**Comment by fritz-fritz** [comment]
@Daegalus that looks to be the HTSP API which is the new and preferred method of interacting with TVH but this channel uses the HTTP API which apparently was updated from version 15 to version 18 recently. At least that's my understanding of it. I'm not sure if Plex supports HTSP streams.

**Comment by realriot** [comment]
I've added a detection for ">=" version 15... That's ok for the moment.
