### ISSUE TITLE
API Version Mismatch even though I'm using version 15

### ISSUE THREAD

**Issue by MikeF09** [realriot/tvheadend-ng.bundle#36]
Hi,

I'm trying to use this plugin with TVHeadend version 4.1.373 but I get an error saying there is an API version mismatch. Below is a copy/paste of my TVHeadend "serverinfo" file I downloaded from TVHeadend showing I am using API version 15, is there something I am doing wrong?

{"sw_version":"4.1.373","api_version":15,"name":"Tvheadend","capabilities":["caclient","tvadapters","satip_client","satip_server","imagecache","timeshift","trace","libav"]}

Any help would be appreciated
Thanks!

**Comment by fritz-fritz** [comment]
Hi, if you have pulled the latest version, @realriot made a change to the minimum required API version which could be breaking things for you. See [here](https://github.com/realriot/tvheadend-ng.bundle/commit/2b07abc0a62a621a098d8babc74e30927a7447a0) for what he changed and [here](https://forums.plex.tv/discussion/comment/1020779/#Comment_1020779) for my proposed alternate solution. I will submit a pull request later if you'd rather wait.

**Comment by MikeF09** [comment]
Thank you very much for the response. I ended up changing the req api version =18 back to 15 as well as implemented the fix you proposed, so if I update TVheadend later it should still work. Everything seems to be working now. Thank you very much.
