### ISSUE TITLE
howto force transcoding in rasplex

### ISSUE THREAD

**Issue by firsttris** [realriot/tvheadend-ng.bundle#41]
Hello,

im using your plugin in rasplex.
it always plays the tvheadend stream directly. Which works perfect for local network.

But using your plugin from remote (rasplex) results in error because tvheadend server is not available.

Using your plugin from iOS or Android => PMS uses transcoding and everything works flawless.
Because it plays from PMS and not directly from tvheadend.

Is there a way to force transcoding for a specific device? e.g. Rasplex Raspberry?

Because no matter what i do Rasplex always plays directly from tvheadend.

regards
firsttris

**Comment by realriot** [comment]
I don't think the raspberry has enough power to transcode... Perhaps the tvh build has no transcoding capabilities?

**Comment by firsttris** [comment]
i think you get me wrong,

plexmediaserver is running on a powerfull server as well as tvheadend.

im using rasplex as a client aka plex home media theater.

i think the problem is related to the plex media server.. 

He decides whenever a stream should be transcoded or not... for mobile-devices or browser plexmediacenter transcodes the incoming MPEG-TS Pass-thru

but for a "plex home theater" client like Rasplex or "Plex Home Theater for Windows" plexmediaserver only sends URL for directplay.

This causes the following issues:  (with plex media theater client)
- you cannot view tvheadend from remote
- you cannot get plexmediaserver to transcode the stream

but i think you cannot change this behavior in your addon, im right?

regards

**Comment by realriot** [comment]
I asked this question very often within the plex developer forums... But didn't get an answer or "it's up to plex to decide".

Since the plex guys don't support me/the community anymore with full power, there are many points often which I cannot solve at the moment. This one for example :-)

**Comment by firsttris** [comment]
thx for your answer
regards
Tristan
