### ISSUE TITLE
Transcoding on Plex MediaServer

### ISSUE THREAD

**Issue by nofear82** [realriot/tvheadend-ng.bundle#42]
Hi, 

I have installed the latest Version and I wount to transcode the TV Streams at the Plex Server, I have 
checked MPEG-TS Pass-Through and the default profile is pass. But I can not get transcodet content. And I cann not set the Bandwith in the client. 
Is ther some option to activate it? 

Arthur

**Comment by realriot** [comment]
Hm, everything you told us is up to plex mediaserver to device. It looks at the stream and compares the capabilites with the client request. The same with the requested bandwidth.
