### ISSUE TITLE
Passing dvb sub-streams to plex.

### ISSUE THREAD

**Issue by jaarsa** [realriot/tvheadend-ng.bundle#44]
I've tried everything to get subtitles selection from tvheadend to my Plex Media Server using this fabulous channel/plugin.

I use the default profile "pass" in my tvheadend-ng.bundle, and with that set, I suppose tvheadend will also pass the sub-streams.

That's in fact not working at all.

Instead I get AUDIO Unknown and SUBTITLES None. Is this a PMS or a plugin problem?

The stream works great in VLC btw.

**Comment by jaarsa** [comment]
![bbc_brit](https://cloud.githubusercontent.com/assets/7510420/12067127/a19b77b0-aff4-11e5-8588-232f9ed5fde9.PNG)

**Comment by realriot** [comment]
This is something what plex/tvh has to offer. This channel just takes the outout and delivers it to the plex server... Sorry,nothing I can do for you at the moment...
