### ISSUE TITLE
Buffer problems with Samsung Smart TV Plex App

### ISSUE THREAD

**Issue by nyhls** [realriot/tvheadend-ng.bundle#45]
Hi, thanks for the great Plugin. This issue is probably not related to the plugin itself, but I hope to find some help here. 
Everything works fine for me, except the most important part. When I open a channel the stream starts after a few seconds of buffering, but it's getting stuck after maybe 10-20 sec to buffer again. I tested the the LAN connection my TV uses with my Laptop and there it plays fine. Even via WiFi the stream is stable on my Laptop. I use the Samsung UE46F6470 as a client. 
Does someone have any idea what I might tweak to get this running?
Best
Niels

**Comment by realriot** [comment]
The channel has no access to any global configurations of plexmediaserver...
